## Numpy :
### A library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.


### why Numpy is better than list:
###### 1) numpy need less more than list
###### 2) numpy is faster than list 
###### 3) numpy is more easy  than list
###### 4) numpy has more functionality

In [3]:
import numpy as np
## create numpy array
a = [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
a = [1,2,3,4,'a',4.5]
b = np.array(a)
print(b)

['1' '2' '3' '4' 'a' '4.5']


#### in above example a numpy array is converted all element in string  because array contain one string value in it  

In [9]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [15]:
np.zeros(2,dtype = int)

array([0, 0])

In [13]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
np.full(4,5)# full (size,value)

array([5, 5, 5, 5])

In [20]:
np.empty(3)

array([1.39358657e-311, 0.00000000e+000, 1.11258871e-307])

In [21]:
# numpy.arange()
b =np.arange(10)

In [22]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b =np.arange(2,21,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
# by default it generate 50 samples
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [31]:
np.linspace(2,10,5,dtype=int,endpoint = True)
# linspace(start,end,no_of_sample,datatype , include end value)

array([ 2,  4,  6,  8, 10])

In [33]:
# generate square array
b = np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
# eye()generate both square and rectangular array
b = np.eye(2,3)
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [38]:
b = np.random.rand(4)
b

array([0.86445324, 0.64883026, 0.57742322, 0.57691651])

In [39]:
b = np.random.rand(10)*10
b

array([1.76643499, 3.17792412, 7.33044989, 8.96779213, 9.41221485,
       2.07535034, 6.62525866, 3.83272354, 1.60522459, 3.41184107])

In [40]:
b = np.random.rand(4,3)
b

array([[0.67734078, 0.80315452, 0.28822162],
       [0.85566395, 0.75588861, 0.86725516],
       [0.73249291, 0.28353535, 0.89088115],
       [0.40668078, 0.90858701, 0.08601611]])

In [56]:
a = [1,2,3,4,5,7,6,8,4]
a = np.array(a)
print(a)

[1 2 3 4 5 7 6 8 4]


In [48]:
print(a.data)
print(a.shape)
print(a.dtype)
print(a.strides)

(9,)
int32
(4,)


In [64]:
# accessing element 1d array
print(a[1])
print(a[4:8])

2
[5 7 6 8]


In [4]:
b = [[1,2,3,4],[1,5,7,8],[3,5,7,7]]
b = np.array(b)
print(b)

[[1 2 3 4]
 [1 5 7 8]
 [3 5 7 7]]


In [66]:
print(b.data)
print(b.shape)
print(b.dtype)
print(b.strides)

(3, 4)
int32
(16, 4)


In [5]:
#access element in 2d array 
print(b[2][1])
print(b[2,1])    

5
5


In [6]:
# access multiple element of same row
print(b[1][1:3])

[5 7]


In [33]:
# access multiple element of same column
print(b[:,3:])

[[4]
 [8]
 [7]]


In [60]:
a = np.random.randint(1,10,5)
b = np.random.randint(1,10,5)
print(a)
print(b)

[6 8 3 6 4]
[9 5 7 6 4]


In [61]:
a+b

array([15, 13, 10, 12,  8])

In [62]:
a*b

array([54, 40, 21, 36, 16])

In [63]:
b-a

array([ 3, -3,  4,  0,  0])

In [64]:
a**b

array([10077696,    32768,     2187,    46656,      256], dtype=int32)

In [65]:
a/b

array([0.66666667, 1.6       , 0.42857143, 1.        , 1.        ])

In [66]:
a//b


array([0, 1, 0, 1, 1], dtype=int32)

In [67]:
print(a)
print(a.sum()) # sum of array
print(a.mean())# mean of array
print(a.min())# minimum value of array
print(a.max())#maximum value of array
print(a.argmin())# index of minimum value of array
print(a.argmax())# index of maximum value of array

[6 8 3 6 4]
27
5.4
3
8
2
1


#### relational operations on array

In [68]:
a>b

array([False,  True, False, False, False])

In [69]:
a==b


array([False, False, False,  True,  True])

In [70]:
a<b

array([ True, False,  True, False, False])

#### Logical operation

In [71]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [72]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [73]:
print(np.logical_not(a))

[False False False False False]


In [74]:
b[2]=0
print(np.logical_not(b))

[False False  True False False]


In [82]:
# print elements which satisfy condition 
n = b[(b<10)& (b>5)]
print(n)

[9 6]


In [83]:
c =b 
c[c<6] =10    

In [84]:
c

array([ 9, 10, 10,  6, 10])

In [87]:
print(b[b==10])

[10 10 10]


In [88]:
# index 
print(np.where(b==10))

(array([1, 2, 4], dtype=int64),)


In [110]:
a = np.random.randint(1,30,(5,6))

In [111]:
a

array([[23, 12, 21, 27,  7, 12],
       [22, 27,  5,  9, 10, 25],
       [17, 10, 27, 27, 21, 26],
       [13, 25,  9,  4,  8, 17],
       [10,  4, 29,  4, 17,  5]])

In [112]:
print(a<20)

[[False  True False False  True  True]
 [False False  True  True  True False]
 [ True  True False False False False]
 [ True False  True  True  True  True]
 [ True  True False  True  True  True]]


In [113]:
print(a[a<20])

[12  7 12  5  9 10 17 10 13  9  4  8 17 10  4  4 17  5]


In [114]:
a[a>20] = 100
a

array([[100,  12, 100, 100,   7,  12],
       [100, 100,   5,   9,  10, 100],
       [ 17,  10, 100, 100, 100, 100],
       [ 13, 100,   9,   4,   8,  17],
       [ 10,   4, 100,   4,  17,   5]])

In [115]:
# find value equal to 100 in particular column (4) change it to 99
b = a[:,4] == 100
a[b,4] = 99
print(a)

[[100  12 100 100   7  12]
 [100 100   5   9  10 100]
 [ 17  10 100 100  99 100]
 [ 13 100   9   4   8  17]
 [ 10   4 100   4  17   5]]


### broadcasting

In [118]:
a = np.random.randint(1,30,(5,5)) 
b = np.random.randint(1,30,(5))

In [119]:
a+b

array([[22, 42, 38, 56, 16],
       [39, 24, 44, 31, 24],
       [26, 27, 43, 29, 23],
       [21, 30, 33, 41, 23],
       [37, 39, 30, 40, 22]])

In [122]:
b = np.random.randint(1,30,(5,4))
c = np.random.randint(1,30,(4,5))
y = np.transpose(c)
y

array([[16, 20, 15, 21],
       [14,  7, 28,  7],
       [ 1, 23, 22,  2],
       [ 8, 11, 10, 16],
       [22, 12,  5, 15]])

In [123]:
b-y

array([[-10, -15,  -5,   0],
       [ -1,  14,   0,  -3],
       [ 22, -14,  -8,  17],
       [ 14,  17,   6, -10],
       [  2,  -6,  19,  13]])